if(EXISTS "/home/hikikomori/Documents/cpplabs/master-programming-task/lab2/tests/iomanip_tests-b12d07c.cmake")
  include("/home/hikikomori/Documents/cpplabs/master-programming-task/lab2/tests/iomanip_tests-b12d07c.cmake")
else()
  add_test(iomanip_NOT_BUILT-b12d07c iomanip_NOT_BUILT-b12d07c)
endif()
